defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

dataset: null 

args: &args
  model_name: "FNO"
  if_training: False
  if_downsample: True
  continue_training: False
  rollout_test: 1
  num_workers: 16
  batch_size: 2 #4 for FNO and 2 for AUX
  initial_step: 10
  t_train: 101
  model_update: 1
  model_flmn: "2D_diff-react_lr1ar07_ep25_bs512_s17"
  FNO_model_flmn: "2D_diff-react_test_ep25_bs128_s17"
  base_path: ../data_gen/data/
  aux_path: ../data_gen/

  epochs: 100
  learning_rate: 1.e-3
  learning_rate_share: 1.e-3
  learning_rate_fc2: 1.e-3
  training_type: "single"
  
  #Auxiliary
  num_aux_samples: 3
  auxiliary_weight: 0.7

  #Scheduler
  scheduler: 'cosine'
  scheduler_step: 100
  scheduler_gamma: 0.5

  #FNO
  num_channels: 2
  modes: 12
  width: 20

  #Plotting
  plot: False
  channel_plot: 0 # Which channel/variable to be plotted
  x_min: -1
  x_max: 1
  y_min: -1
  y_max: 1
  t_min: 0
  t_max: 5

# Define dataset configurations with different subsampling
basic_ds2: 
  <<: *args
  train_subsample: [2, 1, 3]

basic_ds4: 
  <<: *args
  train_subsample: [4, 2, 6]

basic_ds8: 
  <<: *args
  train_subsample: [8, 4, 12]

basic_ds16: 
  <<: *args
  train_subsample: [16, 8, 24]

basic_ds32: 
  <<: *args
  train_subsample: [32, 16, 48]

basic_ds64: 
  <<: *args
  train_subsample: [64, 32, 96]

basic_ds128: 
  <<: *args
  train_subsample: [128, 64, 192]

# basic_ds192: 
#   <<: *args
#   train_subsample: [192, 96, 288]

# basic_ds256: 
#   <<: *args
#   train_subsample: [256, 128, 384]

# basic_ds384: 
#   <<: *args
#   train_subsample: [384, 192, 576]

# basic_ds512:
#   <<: *args
#   train_subsample: [512, 256, 768]

# basic_ds900:
#   <<: *args
#   train_subsample: [900, 900, 900]



# For decomposed downsampling experiments
# basic_ds2: 
#   <<: *args
#   train_subsample: [2, 1, 8]

# basic_ds4: 
#   <<: *args
#   train_subsample: [4, 2, 16]

# basic_ds8: 
#   <<: *args
#   train_subsample: [8, 4, 32]

# basic_ds16: 
#   <<: *args
#   train_subsample: [16, 8, 64]

# basic_ds32: 
#   <<: *args
#   train_subsample: [32, 16, 128]

# basic_ds64: 
#   <<: *args
#   train_subsample: [64, 32, 256]

# basic_ds128: 
#   <<: *args
#   train_subsample: [128, 64, 512]

