# config_transformer_aux_ns_3d.yaml

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

args: &args
  model_name: "TransformerAux3D"
  if_training: True
  continue_training: False
  seed: 0

  num_workers: 16
  batch_size: 4
  grad_accum: 2
  use_amp: true

  initial_step: 10
  training_type: "single"

  learning_rate_share: 1.5e-4
  learning_rate_heads: 1.5e-4
  auxiliary_weight: 0.7
  weight_decay: 5.e-3
  layer_decay: 0.75
  epochs: 80
  scheduler: cosine
  scheduler_step: 100
  scheduler_gamma: 0.5
  warmup_steps: 500

  base_path: "/mnt/3D_ns_aux" # both primary & aux live here
  num_aux_samples: 3
  train_subsample: [900, 900, 900]

  input_size: [50, 50, 89] # (X,Y,Z)
  patch_size: [10, 10, 9]
  tubelet_size: 5
  in_chans: 4

  encoder_embed_dim: 1024
  encoder_num_heads: 32
  depth: 16 # encoder depth
  drop_path_rate: 0.15

  decoder_embed_dim: 768
  decoder_depth: 8 # change to 16 if nRMSE is too high
  decoder_num_heads: 8

  ssl: false # supervised training

  plot: False
  channel_plot: 0
  x_min: -1
  x_max: 1
  y_min: -1
  y_max: 1
  t_min: 0
  t_max: 5

basic_ds2:
  <<: *args
  train_subsample: [2, 1, 3]

basic_ds4:
  <<: *args
  train_subsample: [4, 2, 6]

basic_ds8:
  <<: *args
  train_subsample: [8, 4, 12]

basic_ds16:
  <<: *args
  train_subsample: [16, 8, 24]

basic_ds32:
  <<: *args
  train_subsample: [32, 16, 48]

basic_ds48:
  <<: *args
  train_subsample: [48, 24, 72]

basic_ds64:
  <<: *args
  train_subsample: [64, 32, 96]
